version: "3"

networks:
  default:
    name: default-net
    driver: bridge

volumes:
  cache:
    driver: local

services:
  cache:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
  zookeeper:
    image: zookeeper:3.7.0
    container_name: zookeeper
    restart: "no"
    ports:
      - "2181:2181"

  kafka:
    image: obsidiandynamics/kafka
    container_name: kafka
    restart: "no"
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: DOCKER_INTERNAL:PLAINTEXT,DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: DOCKER_INTERNAL://:29092,DOCKER_EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: DOCKER_INTERNAL://kafka:29092,DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
    depends_on:
      - "kafka"

  ms-job-seekers:
    image: aymenzitouni/ms-job-seekers:latest
    container_name: e-recruitment-ms-job-seekers
    restart: always
    environment:
      spring.kafka.consumer.bootstrap-servers: "kafka:29092"
      SPRING_DATASOURCE_URL: ${DATABASE_MS_JOB_SEEKERS_URL}
      SPRING_DATASOURCE_USERNAME: ${DATABASE_MS_JOB_SEEKERS_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DATABASE_MS_JOB_SEEKERS_PASSWORD}
    ports:
      - "8090:8090"
    depends_on:
      - "kafka"
      - "kafdrop"
      - "zookeeper"

  e-recruitment-ms-auth:
    container_name: e-recruitment-ms-auth
    image: aymenzitouni/ms-auth:latest
    depends_on:
      - "cache"
      - "zookeeper"
      - "kafka"
      - "kafdrop"
    environment:
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      SENDGRID_SENDER_EMAIL: ${SENDGRID_SENDER_EMAIL}
      DATABASE_URL: ${DATABASE_MS_AUTH_URL}
      REDIS_HOST: ${REDIS_HOSTNAME}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_USERNAME: ${REDIS_USERNAME}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      KAFKA_HOST: kafka:29092
    ports:
      - "5000:5000"
    restart: always
