apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-auth
spec:
  selector:
    matchLabels:
      app: ms-auth
  template:
    metadata:
      labels:
        app: ms-auth
    spec:
      containers:
        - name: ms-auth
          image: aymenzitouni/ms-auth:3.0.0
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: SENDGRID_API_KEY
              value: "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"
            - name: SENDGRID_SENDER_EMAIL
              value: "e.recruitment.anem@gmail.com"
            - name: DATABASE_URL
              value: "postgres://nfiyndtgpcjsqr:1d13a3a1bafa0c3d289b2a2e3026783fe5b9c67bbf623c29274e1c5f3f8c50c9@ec2-34-242-84-130.eu-west-1.compute.amazonaws.com:5432/df7ufhqsv177pm"
            - name: REDIS_HOST
              value: "cache"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_USERNAME
              value: "default"
            - name: REDIS_PASSWORD
              value: "eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81"
            - name: KAFKA_HOST
              value: "kafka"

---
apiVersion: v1
kind: Service
metadata:
  name: ms-auth
spec:
  type: LoadBalancer
  selector:
    app: ms-auth
  ports:
    - port: 5000
      targetPort: 5000
